# ⚙️ Data Feature Engineering

### Retail Sales Analysis Project

---

**Instructor Notebook | Session Duration: 1.5–2 Hours**

In the previous sessions, we learned how to **explore**, **assess**, and **clean** our data. Now it's time to take the next big step — **Feature Engineering!**

**Feature Engineering** is the art of creating **new, useful columns** from your existing data. It's one of the most important skills in Data Science because better features lead to better analysis and better predictions.

> 💡 *"Coming up with features is difficult, time-consuming, and requires expert knowledge. Applied machine learning is basically feature engineering."* — Andrew Ng

---

## 🎯 Learning Objectives

By the end of this session, you will be able to:

1. **Understand** what Feature Engineering is and why it matters
2. **Convert** string dates to proper datetime format using `pd.to_datetime()`
3. **Extract** date components — Year, Month, Day, Day of Week
4. **Create** new numerical features from existing columns (Revenue per Unit, Profit Margin, etc.)
5. **Categorize** numerical data into meaningful groups using `pd.cut()` and `np.where()`
6. **Create** boolean/flag features (e.g., High Value, Weekend Order)
7. **Encode** categorical variables for analysis
8. **Apply** all these techniques on the Sales dataset

---

## 📖 Concept Explanation

### What is Feature Engineering?

**Feature Engineering** is the process of using your existing data to create **new columns (features)** that make your dataset more informative and useful for analysis or machine learning.

Think of it like this:

| Real World Analogy | Feature Engineering Equivalent |
|---|---|
| You know someone's birthday → You calculate their **age** | You have a Date column → You extract the **Month** |
| You know price and quantity → You calculate **total cost** | You have Price and Quantity → You create **Revenue per Unit** |
| You see a bill amount → You say it's "**expensive**" or "**cheap**" | You have Revenue → You create a **Revenue Category** (Low/Medium/High) |

### Why is Feature Engineering Important?

Your raw data often doesn't tell the full story. Feature Engineering helps you:

- 📊 **Discover hidden patterns** — Which day of the week gets most sales?
- 🎯 **Improve analysis** — Are high-quantity orders more profitable per unit?
- 🤖 **Prepare data for ML** — Machine learning models need numerical, well-structured features
- 💡 **Answer business questions** — What percentage of orders are "high value"?

### Types of Feature Engineering

| Type | What it does | Example |
|---|---|---|
| **Date Features** | Extract parts of a date | Date → Year, Month, Day, Day Name |
| **Mathematical Features** | Combine numbers with math | Revenue / Quantity = Revenue per Unit |
| **Categorical Features** | Group numbers into categories | Revenue → Low, Medium, High |
| **Boolean/Flag Features** | Create True/False columns | Is the order above ₹1000? Yes/No |
| **Encoding Features** | Convert text to numbers | Electronics → 1, Accessories → 0 |

---

## 💻 Code Examples

### Step 1: Import Libraries and Load Dataset

Let's start by importing the libraries we need and loading our sales dataset.

In [1]:
# ----- Step 1: Import necessary libraries -----

import pandas as pd     # For data manipulation
import numpy as np      # For numerical operations



print("✅ Libraries imported successfully!")

✅ Libraries imported successfully!

In [2]:
# ----- Step 2: Load the sales dataset -----

# Read the Excel file into a DataFrame
df = pd.read_excel('DataSet_used/sales_data_messy.xlsx')

# Check the shape (rows, columns)
print("Dataset Shape:", df.shape)
print()

# View the first 5 rows
df.head()

Dataset Shape: (110, 7)

,Transaction_ID,Date,Product,Category,Price,Quantity,Revenue
0,TXN-1001,2026-01-07,Headphones,Accessories,150.0,2,300
1,TXN-1002,2026-01-20,Smartphone,Electronics,600.0,4,2400
2,TXN-1003,2026-01-29,Smartphone,Electronics,600.0,3,1800
3,TXN-1004,2026-01-15,Headphones,Accessories,150.0,1,150
4,TXN-1005,2026-01-11,Headphones,Accessories,150.0,4,600

---

### Step 2: Date Feature Engineering 📅

The **Date** column is currently stored as a **string** (text). We need to:
1. **Convert** it to datetime format
2. **Extract** useful parts like Year, Month, Day, and Day of Week

#### Why convert to datetime?
- Strings like `"2026-01-07"` are just text — Python doesn't know it's a date
- Datetime format lets us **extract parts**, **sort by date**, and **calculate differences**

In [3]:
# ----- Convert 'Date' column from string to datetime -----

# Before conversion — check the data type
print("BEFORE conversion:")
print(f"  Date column type: {df['Date'].dtype}")
print(f"  Sample value: {df['Date'].iloc[0]}")
print(f"  Type of value: {type(df['Date'].iloc[0])}")
print()

# Convert the 'Date' column to datetime format
# pd.to_datetime() is a powerful function that can parse many date formats
df['Date'] = pd.to_datetime(df['Date'])

# After conversion — verify the change
print("AFTER conversion:")
print(f"  Date column type: {df['Date'].dtype}")
print(f"  Sample value: {df['Date'].iloc[0]}")
print(f"  Type of value: {type(df['Date'].iloc[0])}")
print()
print("✅ Date column converted to datetime successfully!")

BEFORE conversion:
  Date column type: str
  Sample value: 2026-01-07
  Type of value: <class 'str'>

AFTER conversion:
  Date column type: datetime64[us]
  Sample value: 2026-01-07 00:00:00
  Type of value: <class 'pandas.Timestamp'>

✅ Date column converted to datetime successfully!

In [4]:
# ----- Extract Year from Date -----

# .dt is a special accessor for datetime columns
# .dt.year gives us just the year part of the date

df['Order_Year'] = df['Date'].dt.year

# Let's see the result
print("✅ 'Order_Year' column created!")

print(df[['Date', 'Order_Year']].head())

✅ 'Order_Year' column created!
        Date  Order_Year
0 2026-01-07      2026.0
1 2026-01-20      2026.0
2 2026-01-29      2026.0
3 2026-01-15      2026.0
4 2026-01-11      2026.0

In [5]:
# ----- Extract Month from Date -----

# .dt.month gives the month number (1 = January, 2 = February, etc.)
df['Order_Month'] = df['Date'].dt.month

# .dt.month_name() gives the full month name (January, February, etc.)
df['Order_Month_Name'] = df['Date'].dt.month_name()

# Let's see both
print("✅ 'Order_Month' and 'Order_Month_Name' columns created!")
print(df[['Date', 'Order_Month', 'Order_Month_Name']].head())

✅ 'Order_Month' and 'Order_Month_Name' columns created!
        Date  Order_Month Order_Month_Name
0 2026-01-07          1.0          January
1 2026-01-20          1.0          January
2 2026-01-29          1.0          January
3 2026-01-15          1.0          January
4 2026-01-11          1.0          January

In [6]:
# ----- Extract Day and Day of Week from Date -----

# .dt.day gives the day of the month (1-31)
df['Order_Day'] = df['Date'].dt.day

# .dt.day_name() gives the name of the day (Monday, Tuesday, etc.)
df['Day_Name'] = df['Date'].dt.day_name()

# .dt.dayofweek gives a number (0 = Monday, 6 = Sunday)
df['Day_of_Week'] = df['Date'].dt.dayofweek

# Let's see all the date features together
print("✅ Day features created!")
print()
print(df[['Date', 'Order_Day', 'Day_Name', 'Day_of_Week']].head(10))

✅ Day features created!

        Date  Order_Day   Day_Name  Day_of_Week
0 2026-01-07        7.0  Wednesday          2.0
1 2026-01-20       20.0    Tuesday          1.0
2 2026-01-29       29.0   Thursday          3.0
3 2026-01-15       15.0   Thursday          3.0
4 2026-01-11       11.0     Sunday          6.0
5 2026-01-08        8.0   Thursday          3.0
6 2026-01-29       29.0   Thursday          3.0
7 2026-01-21       21.0  Wednesday          2.0
8 2026-01-07        7.0  Wednesday          2.0
9        NaT        NaN        NaN          NaN

#### 📋 Summary of `.dt` accessor methods:

| Code | What it extracts | Example Output |
|---|---|---|
| `df['Date'].dt.year` | Year | 2026 |
| `df['Date'].dt.month` | Month number | 1 (January) |
| `df['Date'].dt.month_name()` | Month name | January |
| `df['Date'].dt.day` | Day of month | 7 |
| `df['Date'].dt.day_name()` | Day name | Wednesday |
| `df['Date'].dt.dayofweek` | Day number (0=Mon) | 2 (Wednesday) |
| `df['Date'].dt.quarter` | Quarter | 1 (Q1) |
| `df['Date'].dt.week` | Week number | 2 |

> 💡 **Remember**: The `.dt` accessor ONLY works on datetime columns. If your column is a string, convert it first with `pd.to_datetime()`!

---

### Step 3: Mathematical Feature Engineering 🔢

Now let's create new features by doing **math** on existing columns.

This is like a shopkeeper calculating:
- "How much did I earn **per item** sold?"
- "What **percentage** of revenue is my profit?"

In [7]:
# ----- Feature: Revenue per Unit -----

# Revenue per Unit = Total Revenue / Quantity
# This tells us how much revenue each single unit generated

df['Revenue_Per_Unit'] = df['Revenue'] / df['Quantity']

# Let's see the result
print("✅ 'Revenue_Per_Unit' column created!")
print()
print(df[['Product', 'Price', 'Quantity', 'Revenue', 'Revenue_Per_Unit']].sample(10))

✅ 'Revenue_Per_Unit' column created!

       Product   Price  Quantity  Revenue  Revenue_Per_Unit
9   Smartwatch   200.0         4      800             200.0
63  Smartwatch   200.0         3      600             200.0
77  Headphones   150.0         1      150             150.0
75      Laptop  1000.0         3     3000            1000.0
81  Headphones   150.0         4      600             150.0
72  Smartphone   600.0         4     2400             600.0
27      Tablet   400.0         4     1600             400.0
62  Headphones   150.0         2      300             150.0
70      Tablet   400.0         2      800             400.0
59      Laptop  1000.0         1     1000            1000.0

In [8]:
# ----- Feature: Total Cost (simulated) -----

# In real business, Cost = Price × some cost factor
# Let's assume the cost is 60% of the selling price (40% margin)
# This is a common practice when actual cost data isn't available

cost_percentage = 0.60 # 60% of price is the cost

df['Cost'] = df['Price'] * cost_percentage * df['Quantity']

print("✅ 'Cost' column created! (Assuming cost = 60% of selling price)")
print()
print(df[['Product', 'Price', 'Quantity', 'Revenue', 'Cost']].head())

✅ 'Cost' column created! (Assuming cost = 60% of selling price)

      Product  Price  Quantity  Revenue    Cost
0  Headphones  150.0         2      300   180.0
1  Smartphone  600.0         4     2400  1440.0
2  Smartphone  600.0         3     1800  1080.0
3  Headphones  150.0         1      150    90.0
4  Headphones  150.0         4      600   360.0

In [11]:
# ----- Feature: Profit -----

# Profit = Revenue - Cost
# This tells us how much money we actually made on each transaction

df['Profit'] = df['Revenue'] - df['Cost']

print("✅ 'Profit' column created!")
print()
print(df[['Product', 'Revenue', 'Cost', 'Profit']].sample(10))

✅ 'Profit' column created!

        Product  Revenue    Cost  Profit
13   Headphones      750   450.0   300.0
87       Laptop     4000  2400.0  1600.0
96       Laptop     3000  1800.0  1200.0
27       Tablet     1600   960.0   640.0
54   Smartphone      600   360.0   240.0
82       Tablet      400   240.0   160.0
9    Smartwatch      800   480.0   320.0
17   Smartwatch      200   120.0    80.0
85       Laptop     1000   600.0   400.0
104      Tablet     1600   960.0   640.0

In [12]:
# ----- Feature: Profit Margin (%) -----

# Profit Margin = (Profit / Revenue) × 100
# This tells us what percentage of revenue is actual profit

df['Profit_Margin'] = (df['Profit'] / df['Revenue']) * 100

# Round to 2 decimal places for clean output
df['Profit_Margin'] = df['Profit_Margin'].round(2)

print("✅ 'Profit_Margin' column created!")
print()
print(df[['Product', 'Revenue', 'Profit', 'Profit_Margin']].head(10))
print()
print(f"📊 Average Profit Margin: {df['Profit_Margin'].mean():.2f}%")

✅ 'Profit_Margin' column created!

      Product  Revenue  Profit  Profit_Margin
0  Headphones      300   120.0           40.0
1  Smartphone     2400   960.0           40.0
2  Smartphone     1800   720.0           40.0
3  Headphones      150    60.0           40.0
4  Headphones      600   240.0           40.0
5      Laptop     1000   400.0           40.0
6  Smartwatch      200    80.0           40.0
7  Smartwatch      400   160.0           40.0
8  Smartphone     2400   960.0           40.0
9  Smartwatch      800   320.0           40.0

📊 Average Profit Margin: 40.00%

---

### Step 4: Categorical Feature Engineering 🏷️

Sometimes numbers are more useful when we put them into **groups** or **categories**.

For example:
- Revenue of ₹300 → "**Low Revenue**"
- Revenue of ₹1500 → "**Medium Revenue**"
- Revenue of ₹4000 → "**High Revenue**"

We'll learn two methods:
1. **`pd.cut()`** — for cutting data into fixed bins
2. **`np.where()`** — for simple if/else conditions

In [9]:
# ----- Feature: Revenue Category using pd.cut() -----

# pd.cut() divides a numerical column into bins (groups)
# We define the boundaries: 0-500 = Low, 500-2000 = Medium, 2000-5000 = High

# Define the bin edges
bins = [0, 500, 2000, 5000]

# Define the labels for each bin
labels = ['Low', 'Medium', 'High']

# Create the new column
df['Revenue_Category'] = pd.cut(
    df['Revenue'],       # Column to categorize
    bins=bins,           # The boundary values
    labels=labels        # Labels for each group
)

print("✅ 'Revenue_Category' column created!")
print()
print(df[['Product', 'Revenue', 'Revenue_Category']].head(10))
print()
print("📊 Distribution of Revenue Categories:")
print(df['Revenue_Category'].value_counts())

✅ 'Revenue_Category' column created!

      Product  Revenue Revenue_Category
0  Headphones      300              Low
1  Smartphone     2400             High
2  Smartphone     1800           Medium
3  Headphones      150              Low
4  Headphones      600           Medium
5      Laptop     1000           Medium
6  Smartwatch      200              Low
7  Smartwatch      400              Low
8  Smartphone     2400             High
9  Smartwatch      800           Medium

📊 Distribution of Revenue Categories:
Revenue_Category
Medium    52
Low       31
High      27
Name: count, dtype: int64

In [10]:
# ----- Feature: Quantity Category using np.where() -----

# np.where() works like an IF-ELSE statement
# Syntax: np.where(condition, value_if_true, value_if_false)

# Let's classify orders:
# If Quantity >= 3 → "Bulk Order"
# Otherwise → "Regular Order"

df['Order_Type'] = np.where(
    df['Quantity'] >= 3,      # Condition
    'Bulk Order',             # Value if True
    'Regular Order'           # Value if False
)

print("✅ 'Order_Type' column created!")
print()
print(df[['Product', 'Quantity', 'Order_Type']].head(10))
print()
print("📊 Distribution:")
print(df['Order_Type'].value_counts())

✅ 'Order_Type' column created!

      Product  Quantity     Order_Type
0  Headphones         2  Regular Order
1  Smartphone         4     Bulk Order
2  Smartphone         3     Bulk Order
3  Headphones         1  Regular Order
4  Headphones         4     Bulk Order
5      Laptop         1  Regular Order
6  Smartwatch         1  Regular Order
7  Smartwatch         2  Regular Order
8  Smartphone         4     Bulk Order
9  Smartwatch         4     Bulk Order

📊 Distribution:
Order_Type
Bulk Order       61
Regular Order    49
Name: count, dtype: int64

In [11]:
# ----- Feature: Price Tier using multiple conditions with np.select() -----

# What if we have MORE than 2 categories?
# np.where() only handles 2 (if/else)
# np.select() can handle multiple conditions!

# Define the conditions
conditions = [
    df['Price'] <= 200,                          # Condition 1: Budget
    (df['Price'] > 200) & (df['Price'] <= 600),  # Condition 2: Mid-Range
    df['Price'] > 600                             # Condition 3: Premium
]

# Define the values for each condition
choices = ['Budget', 'Mid-Range', 'Premium']

# Create the column
df['Price_Tier'] = np.select(conditions, choices, default='Unknown')

print("✅ 'Price_Tier' column created!")
print()
print(df[['Product', 'Price', 'Price_Tier']].drop_duplicates().sort_values('Price'))
print()
print("📊 Distribution:")
print(df['Price_Tier'].value_counts())

✅ 'Price_Tier' column created!

       Product   Price Price_Tier
0   Headphones   150.0     Budget
6   Smartwatch   200.0     Budget
76         NaN   200.0     Budget
24      Tablet   400.0  Mid-Range
1   Smartphone   600.0  Mid-Range
5       Laptop  1000.0    Premium
39         NaN  1000.0    Premium
36      Laptop     NaN    Unknown
66  Smartwatch     NaN    Unknown

📊 Distribution:
Price_Tier
Budget       43
Mid-Range    37
Premium      27
Unknown       3
Name: count, dtype: int64

#### 📋 When to use which method?

| Method | Best For | Example |
|---|---|---|
| `np.where()` | **2 categories** (if/else) | High Value: Yes / No |
| `np.select()` | **3+ categories** (if/elif/else) | Budget / Mid-Range / Premium |
| `pd.cut()` | **Equal-width bins** on numbers | Low / Medium / High |
| `pd.qcut()` | **Equal-frequency bins** | Bottom 25% / Middle 50% / Top 25% |
| `.map()` | **Mapping exact values** | Product → Category |
| `.apply()` | **Complex custom logic** | Custom function on each row |

---

### Step 5: Boolean (Flag) Feature Engineering 🚩

Boolean features are **True/False** columns that act as flags or indicators.

They are useful for:
- Quickly filtering data
- Counting how many rows meet a condition
- Using as features in machine learning

In [12]:
# ----- Feature: Is Weekend? -----

# Day_of_Week: 0=Monday, 1=Tuesday, ..., 5=Saturday, 6=Sunday
# Weekend means Day_of_Week is 5 (Saturday) or 6 (Sunday)

df['Is_Weekend'] = df['Day_of_Week'] >= 5

print("✅ 'Is_Weekend' column created!")
print()
print(df[['Date', 'Day_Name', 'Day_of_Week', 'Is_Weekend']].head(10))
print()
print(f"📊 Weekend orders: {df['Is_Weekend'].sum()} out of {len(df)}")
print(f"   Weekday orders: {(~df['Is_Weekend']).sum()} out of {len(df)}")

✅ 'Is_Weekend' column created!

        Date   Day_Name  Day_of_Week  Is_Weekend
0 2026-01-07  Wednesday          2.0       False
1 2026-01-20    Tuesday          1.0       False
2 2026-01-29   Thursday          3.0       False
3 2026-01-15   Thursday          3.0       False
4 2026-01-11     Sunday          6.0        True
5 2026-01-08   Thursday          3.0       False
6 2026-01-29   Thursday          3.0       False
7 2026-01-21  Wednesday          2.0       False
8 2026-01-07  Wednesday          2.0       False
9        NaT        NaN          NaN       False

📊 Weekend orders: 27 out of 110
   Weekday orders: 83 out of 110

In [13]:
# ----- Feature: Is High Value Order? -----

# Let's flag orders where Revenue is above ₹1000

df['Is_High_Value'] = df['Revenue'] > 1000

print("✅ 'Is_High_Value' column created! (Revenue > ₹1000)")
print()
print(df[['Product', 'Revenue', 'Is_High_Value']].head(10))
print()
print(f"📊 High value orders: {df['Is_High_Value'].sum()} ({df['Is_High_Value'].mean()*100:.1f}%)")
print(f"   Regular orders:    {(~df['Is_High_Value']).sum()} ({(~df['Is_High_Value']).mean()*100:.1f}%)")

✅ 'Is_High_Value' column created! (Revenue > ₹1000)

      Product  Revenue  Is_High_Value
0  Headphones      300          False
1  Smartphone     2400           True
2  Smartphone     1800           True
3  Headphones      150          False
4  Headphones      600          False
5      Laptop     1000          False
6  Smartwatch      200          False
7  Smartwatch      400          False
8  Smartphone     2400           True
9  Smartwatch      800          False

📊 High value orders: 44 (40.0%)
   Regular orders:    66 (60.0%)

In [20]:
# ----- Feature: Is Multi-Unit Order? -----

# Flag orders where more than 1 unit was purchased

df['Is_Multi_Unit'] = df['Quantity'] > 1

print("✅ 'Is_Multi_Unit' column created! (Quantity > 1)")
print()
print(df[['Product', 'Quantity', 'Is_Multi_Unit']].head(10))
print()
print(f"📊 Multi-unit orders: {df['Is_Multi_Unit'].sum()} ({df['Is_Multi_Unit'].mean()*100:.1f}%)")

✅ 'Is_Multi_Unit' column created! (Quantity > 1)

      Product  Quantity  Is_Multi_Unit
0  Headphones         2           True
1  Smartphone         4           True
2  Smartphone         3           True
3  Headphones         1          False
4  Headphones         4           True
5      Laptop         1          False
6  Smartwatch         1          False
7  Smartwatch         2           True
8  Smartphone         4           True
9  Smartwatch         4           True

📊 Multi-unit orders: 81 (73.6%)

> 💡 **Pro Tip**: Boolean columns are secretly 0s and 1s!
> - `True` = 1, `False` = 0
> - So `df['Is_Weekend'].sum()` counts how many `True` values there are
> - And `df['Is_Weekend'].mean()` gives the proportion (percentage) of `True` values

---

### Step 6: Encoding Categorical Variables 🔄

Machine Learning models and many analysis techniques need **numbers**, not text. So we need to convert categorical (text) columns into numbers.

Two common methods:
1. **Label Encoding** — Convert each category to a unique number
2. **One-Hot Encoding** — Create a separate column for each category with 0/1 values

In [21]:
# ----- Method 1: Label Encoding using .map() -----

# We manually map each category to a number
# This works well when there are only a few categories

# Our dataset has 2 categories: Electronics and Accessories
category_mapping = {
    'Electronics': 1,
    'Accessories': 0
}

# Apply the mapping
df['Category_Encoded'] = df['Category'].map(category_mapping)

print("✅ 'Category_Encoded' column created using Label Encoding!")
print()
print(df[['Category', 'Category_Encoded']].drop_duplicates())
print()
print("Mapping used:")
for key, value in category_mapping.items():
    print(f"  {key} → {value}")

✅ 'Category_Encoded' column created using Label Encoding!

       Category  Category_Encoded
0   Accessories               0.0
1   Electronics               1.0
41          NaN               NaN

Mapping used:
  Electronics → 1
  Accessories → 0

In [22]:
# ----- Method 2: One-Hot Encoding using pd.get_dummies() -----

# One-Hot Encoding creates a NEW column for EACH unique category
# Each column has 1 if that row belongs to that category, 0 otherwise

# Let's one-hot encode the 'Product' column
product_dummies = pd.get_dummies(
    df['Product'],          # Column to encode
    prefix='Product'        # Prefix for new column names
)

print("✅ One-Hot Encoding of 'Product' column:")
print()
print(product_dummies.head(10))
print()
print(f"📊 Original 'Product' column had {df['Product'].nunique()} unique values")
print(f"   One-Hot Encoding created {product_dummies.shape[1]} new columns")

✅ One-Hot Encoding of 'Product' column:

   Product_Headphones  Product_Laptop  Product_Smartphone  Product_Smartwatch  \
0                True           False               False               False
1               False           False                True               False
2               False           False                True               False
3                True           False               False               False
4                True           False               False               False
5               False            True               False               False
6               False           False               False                True
7               False           False               False                True
8               False           False                True               False
9               False           False               False                True

   Product_Tablet
0           False
1           False
2           False
3           False
4           False
5           False
6           False
7           False
8           False
9           False

📊 Original 'Product' column had 5 unique values
   One-Hot Encoding created 5 new columns

In [23]:
# ----- Add the one-hot encoded columns to our DataFrame -----

# Use pd.concat() to join the dummy columns with our main DataFrame
df = pd.concat([df, product_dummies], axis=1)

print("✅ One-hot encoded columns added to DataFrame!")
print()
print(f"DataFrame now has {df.shape[1]} columns (up from 7 original columns!)")
print()
print("New columns added:")
for col in product_dummies.columns:
    print(f"  • {col}")

✅ One-hot encoded columns added to DataFrame!

DataFrame now has 29 columns (up from 7 original columns!)

New columns added:
  • Product_Headphones
  • Product_Laptop
  • Product_Smartphone
  • Product_Smartwatch
  • Product_Tablet

#### 📋 Label Encoding vs One-Hot Encoding

| Aspect | Label Encoding | One-Hot Encoding |
|---|---|---|
| **How it works** | Assigns a number to each category | Creates a column per category |
| **Example** | Electronics=1, Accessories=0 | Product_Laptop=1, Product_Tablet=0 |
| **Best for** | 2 categories or ordered categories | 3+ unordered categories |
| **Risk** | Model may think 1 > 0 (order matters) | Creates many columns if many categories |
| **Method** | `.map()` or `LabelEncoder` | `pd.get_dummies()` |

---

### Step 7: Using `.apply()` for Custom Features 🛠️

Sometimes you need **custom logic** that's too complex for `np.where()`. In that case, use `.apply()` with a custom function.

In [24]:
# ----- Feature: Revenue Label using a custom function with .apply() -----

# Define a function that takes a revenue value and returns a label
def classify_revenue(revenue):
    """Classify revenue into descriptive labels."""
    if revenue >= 3000:
        return '🟢 Excellent'
    elif revenue >= 1500:
        return '🟡 Good'
    elif revenue >= 500:
        return '🟠 Average'
    else:
        return '🔴 Low'

# Apply the function to each value in the 'Revenue' column
df['Revenue_Label'] = df['Revenue'].apply(classify_revenue)

print("✅ 'Revenue_Label' column created using .apply()!")
print()
print(df[['Product', 'Revenue', 'Revenue_Label']].head(10))
print()
print("📊 Distribution:")
print(df['Revenue_Label'].value_counts())

✅ 'Revenue_Label' column created using .apply()!

      Product  Revenue Revenue_Label
0  Headphones      300         🔴 Low
1  Smartphone     2400        🟡 Good
2  Smartphone     1800        🟡 Good
3  Headphones      150         🔴 Low
4  Headphones      600     🟠 Average
5      Laptop     1000     🟠 Average
6  Smartwatch      200         🔴 Low
7  Smartwatch      400         🔴 Low
8  Smartphone     2400        🟡 Good
9  Smartwatch      800     🟠 Average

📊 Distribution:
Revenue_Label
🟠 Average      40
🔴 Low          31
🟢 Excellent    21
🟡 Good         18
Name: count, dtype: int64

In [17]:
# ----- Feature: Using .apply() with lambda (short functions) -----

# Lambda functions are one-line shortcut functions
# Great for simple transformations

# Example: Create a 'Transaction_Number' by extracting the number from Transaction_ID
# 'TXN-1001' → 1001
import pandas as pd

df=pd.read_excel("DataSet_used/sales_data_messy.xlsx")
df=df.dropna(subset="Transaction_ID")
print(df["Transaction_ID"].isnull().sum().sum())
print(df["Transaction_ID"].dtype)
df['Transaction_Number'] =(df['Transaction_ID'].apply(lambda x:(x.split("-"))))

print("✅ 'Transaction_Number' extracted using lambda + .apply()!")
print()
print(df[['Transaction_ID', 'Transaction_Number']].head())
print()
print("How it works:")
print("  'TXN-1001'.split('-') → ['TXN', '1001']")
print("  ['TXN', '1001'][1]   → '1001'")
print("  int('1001')          → 1001")

0
str
✅ 'Transaction_Number' extracted using lambda + .apply()!

  Transaction_ID Transaction_Number
0       TXN-1001        [TXN, 1001]
1       TXN-1002        [TXN, 1002]
2       TXN-1003        [TXN, 1003]
3       TXN-1004        [TXN, 1004]
4       TXN-1005        [TXN, 1005]

How it works:
  'TXN-1001'.split('-') → ['TXN', '1001']
  ['TXN', '1001'][1]   → '1001'
  int('1001')          → 1001

---

### Step 8: Review All New Features 📊

Let's take a step back and see everything we've created!

In [ ]:
# ----- Review: All columns in our DataFrame -----

print("📊 Complete Column List")
print("=" * 50)
print()

# Original columns
original_cols = ['Transaction_ID', 'Date', 'Product', 'Category', 'Price', 'Quantity', 'Revenue']

print("📁 ORIGINAL COLUMNS (7):")
for col in original_cols:
    print(f"  • {col}")

print()

# New columns
new_cols = [col for col in df.columns if col not in original_cols]
print(f"✨ NEW ENGINEERED FEATURES ({len(new_cols)}):")
for col in new_cols:
    print(f"  • {col}")

print()
print(f"Total columns: {len(original_cols)} original + {len(new_cols)} new = {df.shape[1]} columns")

📊 Complete Column List
==================================================

📁 ORIGINAL COLUMNS (7):
  • Transaction_ID
  • Date
  • Product
  • Category
  • Price
  • Quantity
  • Revenue

✨ NEW ENGINEERED FEATURES (12):
  • Order_Year
  • Order_Month
  • Order_Month_Name
  • Order_Day
  • Day_Name
  • Day_of_Week
  • Cost
  • Profit
  • Profit_Margin
  • Order_Type
  • Price_Tier
  • Transaction_Number

Total columns: 7 original + 12 new = 19 columns

In [ ]:
# ----- View the final DataFrame -----

# Show a sample of key columns
key_columns = [
    'Transaction_ID', 'Date', 'Product', 'Category',
    'Price', 'Quantity', 'Revenue',
    'Order_Month', 'Day_Name', 'Is_Weekend',
    'Revenue_Per_Unit', 'Profit', 'Profit_Margin',
    'Revenue_Category', 'Price_Tier', 'Order_Type'
]

print("📊 Final DataFrame — Key Features:")
df[key_columns].head(10)

📊 Final DataFrame — Key Features:

,Transaction_ID,Date,Product,Category,Price,Quantity,Revenue,Order_Month,Day_Name,Is_Weekend,Revenue_Per_Unit,Profit,Profit_Margin,Revenue_Category,Price_Tier,Order_Type
0,TXN-1001,2026-01-07,Headphones,Accessories,150,2,300,1,Wednesday,False,150.0,120.0,40.0,Low,Budget,Regular Order
1,TXN-1002,2026-01-20,Smartphone,Electronics,600,4,2400,1,Tuesday,False,600.0,960.0,40.0,High,Mid-Range,Bulk Order
2,TXN-1003,2026-01-29,Smartphone,Electronics,600,3,1800,1,Thursday,False,600.0,720.0,40.0,Medium,Mid-Range,Bulk Order
3,TXN-1004,2026-01-15,Headphones,Accessories,150,1,150,1,Thursday,False,150.0,60.0,40.0,Low,Budget,Regular Order
4,TXN-1005,2026-01-11,Headphones,Accessories,150,4,600,1,Sunday,True,150.0,240.0,40.0,Medium,Budget,Bulk Order
5,TXN-1006,2026-01-08,Laptop,Electronics,1000,1,1000,1,Thursday,False,1000.0,400.0,40.0,Medium,Premium,Regular Order
6,TXN-1007,2026-01-29,Smartwatch,Accessories,200,1,200,1,Thursday,False,200.0,80.0,40.0,Low,Budget,Regular Order
7,TXN-1008,2026-01-21,Smartwatch,Accessories,200,2,400,1,Wednesday,False,200.0,160.0,40.0,Low,Budget,Regular Order
8,TXN-1009,2026-01-07,Smartphone,Electronics,600,4,2400,1,Wednesday,False,600.0,960.0,40.0,High,Mid-Range,Bulk Order
9,TXN-1010,2026-01-26,Smartwatch,Accessories,200,4,800,1,Monday,False,200.0,320.0,40.0,Medium,Budget,Bulk Order

### Task 1: Extract the **Week Number** from the Date column
Create a column called `'Week_Number'` using the `.dt` accessor.

**Hint:** Use `.dt.isocalendar().week`

In [26]:
# Task 1: Your code here
df["Date"].dt.isocalendar().week

0      2
1      4
2      5
3      3
4      2
      ..
105    5
106    1
107    2
108    4
109    2
Name: week, Length: 110, dtype: UInt32

### Task 2: Create a **"Quarter"** column
Extract the quarter from the Date column (Q1, Q2, Q3, Q4).

**Hint:** Use `.dt.quarter`

In [28]:
# Task 2: Your code here

df["Date"].dt.quarter

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
105    1.0
106    1.0
107    1.0
108    1.0
109    1.0
Name: Date, Length: 110, dtype: float64

### Task 3: Create a **"Discount_Price"** column
Assume a flat 10% discount on all products. Calculate the discounted price.

**Formula:** `Discount_Price = Price × 0.90`

In [ ]:
# Task 3: Your code here

### Task 4: Create a **"Quantity_Category"** column
Categorize Quantity into:
- 1 unit → "Single"
- 2-3 units → "Few"
- 4-5 units → "Many"

**Hint:** Use `pd.cut()` with bins `[0, 1, 3, 5]` and labels `['Single', 'Few', 'Many']`

In [ ]:
# Task 4: Your code here

### Task 5: Create an **"Is_Expensive"** flag
Flag products that cost more than ₹500 as `True`, otherwise `False`.

**Hint:** Simple boolean comparison on the Price column.

### Task 6: Create a **"Revenue_Rank"** column
Rank all transactions by Revenue from highest to lowest.

**Hint:** Use `.rank(ascending=False)`

In [18]:
# Task 6: Your code here
df["Revenue_rank"]=df["Revenue"].rank(ascending=False)
print(df[["Revenue","Revenue_rank"]])

     Revenue  Revenue_rank
0        300          91.0
1       2400          24.5
2       1800          31.0
3        150         102.5
4        600          71.5
..       ...           ...
105     4000           6.0
106     1000          49.5
107      450          80.5
108     1200          42.0
109      300          91.0

[107 rows x 2 columns]

### Task 7: Create **"Product_Initial"** column
Extract just the first letter of each Product name.

**Hint:** Use `.apply(lambda x: x[0])`

In [ ]:
# Task 7: Your code here

### Task 8: Create a **"Revenue_Per_Rupee_Price"** column
Calculate how much revenue is generated for every ₹1 of product price.

**Formula:** `Revenue / Price`

💡 This is essentially the Quantity — but it's a good exercise!

In [ ]:
# Task 8: Your code here

### Task 9: One-Hot Encode the **"Category"** column
Use `pd.get_dummies()` to create binary columns for each category.

**Hint:** Use `pd.get_dummies(practice_df['Category'], prefix='Cat')`

In [ ]:
# Task 9: Your code here

### Task 10: Create a **"Transaction_Summary"** string column
Combine Product and Revenue into a descriptive string like:
`"Laptop - ₹3000"`

**Hint:** Use `.apply()` with a lambda on axis=1, or string concatenation.

In [ ]:
# Task 10: Your code here

---

## 📋 Assignment

### Day 4 Project Task: Feature Engineering

**Objective:** Create new useful columns from the `sales_data.xlsx` dataset that will help in business analysis and machine learning. Feature engineering helps transform raw data into meaningful information.

---

#### Instructions:

Complete the following tasks in a **new notebook section** named **"Day 4: Feature Engineering"**.

**1. Convert Date Column**
- Convert the `"Date"` column to datetime format using `pd.to_datetime()`

**2. Create Order Year**
- Create a new column `"Order_Year"` from the Date column

**3. Create Order Month**
- Create a new column `"Order_Month"` from the Date column

**4. Create Day of Week**
- Create a new column `"Day_of_Week"` with the name of the day

**5. Create Revenue Per Unit**
- Create a new column `"Revenue_Per_Unit"` using Revenue and Quantity

**6. Create Revenue Category**
- Create a new column `"Revenue_Category"`
- Label rows as: Low (≤500), Medium (501–2000), High (>2000)

**7. Create High Value Flag**
- Create a new column `"Is_High_Value"`
- Label rows as `True` if Revenue > 1000, otherwise `False`

---

#### Questions to Answer:

1. Which **day of the week** has the most orders?
2. How many orders are **High Value**?
3. What is the **average Revenue Per Unit** for each product?
4. How many orders fall in each **Revenue Category** (Low/Medium/High)?
5. Which **product** has the highest average revenue?

---

#### Deliverables:

1. New columns created (all 7)
2. Output of `df.head(10)`
3. Answers to all 5 questions
4. 3–5 observations from the analysis

---

**Submit your completed notebook.**

In [ ]:
# ==========================================
#   Day 4: Feature Engineering — Assignment
#   Write your code below
# ==========================================

# Step 1: Import libraries and load data


# Step 2: Convert Date column


# Step 3: Create Order_Year


# Step 4: Create Order_Month


# Step 5: Create Day_of_Week


# Step 6: Create Revenue_Per_Unit


# Step 7: Create Revenue_Category


# Step 8: Create Is_High_Value


# Step 9: Display df.head(10)


# Step 10: Answer the questions

---

## 🔑 Key Takeaways

| # | Concept | What You Learned |
|---|---|---|
| 1 | **Feature Engineering** | Creating new, useful columns from existing data |
| 2 | **Date Conversion** | Use `pd.to_datetime()` to convert strings to dates |
| 3 | **Date Extraction** | Use `.dt.year`, `.dt.month`, `.dt.day_name()` to extract date parts |
| 4 | **Math Features** | Combine columns with arithmetic: `Revenue / Quantity` |
| 5 | **Categorization** | Use `pd.cut()` for bins, `np.where()` for if/else, `np.select()` for multiple conditions |
| 6 | **Boolean Flags** | Create True/False columns with comparisons: `df['Revenue'] > 1000` |
| 7 | **Encoding** | Label Encoding (`.map()`) and One-Hot Encoding (`pd.get_dummies()`) |
| 8 | **Custom Functions** | Use `.apply()` with regular or lambda functions for complex logic |

### 📌 Quick Reference — When to Use What?

| I want to... | Use this |
|---|---|
| Convert string to date | `pd.to_datetime()` |
| Get year/month from date | `.dt.year`, `.dt.month` |
| Divide/multiply columns | `df['A'] / df['B']` |
| Create 2 categories | `np.where(condition, 'A', 'B')` |
| Create 3+ categories | `np.select()` or `pd.cut()` |
| Create True/False flag | `df['col'] > value` |
| Map text to numbers | `.map({'A': 1, 'B': 0})` |
| One-hot encode | `pd.get_dummies()` |
| Apply custom logic | `.apply(function)` |

---

### 🚀 What's Next?

In the next session, we'll learn about **Data Visualization** — turning our engineered features into beautiful charts and graphs that tell a story!

---

*Feature Engineering Notebook — Retail Sales Analysis Project*